voice_group friendventure         
	voice_keysplit voicegroup_flute_keysplit, keysplit_flute
	voice_square_2 60, 0, 0, 0, 1, 4, 1 
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_shamisen, 245, 50, 255, 250
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fretless_bass                , 245, 253,   10, 188 
	voice_directsound 60, 0, DirectSoundWaveData_ethnic_flavours_kotsuzumi            , 255,   0, 255,   0 
	voice_keysplit_all voicegroup_rs_drumset
	voice_noise 60, 0, 0, 0, 1, 7, 1 
	voice_programmable_wave 60, 0, ProgrammableWaveData_5, 0, 7, 15, 0  
