voice_group hh_chii_town
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ 0
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fingered_bass, 200, 204, 113, 235
	voice_keysplit voicegroup_piano_keysplit, keysplit_piano
	voice_keysplit_all voicegroup192
	voice_keysplit voicegroup_flute_keysplit, keysplit_flute 
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 255, 249, 25, 76
	voice_directsound 60, 0, DirectSoundWaveData_dp_whistle_c5_16, 255, 247, 160, 200
	voice_programmable_wave_alt 64, 0, ProgrammableWaveData_3, 0, 7, 15, 1
