voice_group hh_chii_town
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ 0
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fingered_bass, 255, 253, 0, 149					
	voice_keysplit voicegroup_piano_keysplit, keysplit_piano
	voice_keysplit_all voicegroup192
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_flute, 255, 0, 255, 165
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_nylon_str_guitar, 255, 249, 25, 76
	voice_directsound 60, 0, DirectSoundWaveData_dp_whistle_c5_16, 255, 247, 160, 200
	voice_square_1 60, 0, 12, 2, 0, 0, 15, 0									
	voice_noise 60, 0, 0, 250, 255, 100, 50
