voice_group offset
	voice_keysplit voicegroup_flute_keysplit, keysplit_flute
	voice_square_2_alt 60, 0,   3,   0,   1,  8, 1
	voice_square_1_alt 60, 0, 0,   1,   0, 1, 5, 1
	voice_square_1_alt 60, 0,  0,  3, 0, 1, 4, 1
	voice_square_1_alt 60, 0, 0,   1,   0, 1, 5, 1
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_piano1_60                    , 255, 250,   0, 221
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fretless_bass                , 255, 253,   0, 188
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_organ2                       , 255,   0, 255, 210
	voice_keysplit_all voicegroup192
	voice_noise_alt 60, 0, 0, 0, 1, 0, 1
