voice_group shop
	voice_square_1 60, 0, 0, 2, 0, 250, 15, 180											@ 0
	voice_keysplit voicegroup_piano_keysplit, keysplit_piano
    voice_square_1 60, 0, 0, 2, 0, 0, 15, 200	
	voice_keysplit voicegroup_flute_keysplit, keysplit_flute
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_pizzicato_strings, 255, 216, 0, 165
	voice_keysplit_all voicegroup192
	voice_noise_alt 96, 0, 0, 0, 1, 0, 0
	voice_programmable_wave_alt 60, 0, ProgrammableWaveData_8, 0, 7, 15, 2

