voice_group snow         
	voice_keysplit_all voicegroup192
	voice_keysplit voicegroup_piano_keysplit, keysplit_piano
   	voice_directsound 60, 0, DirectSoundWaveData_dp_flute_c5_16, 255, 127, 231, 127 
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_harp, 255, 242, 51, 242  
   	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_shamisen, 255, 200, 255, 250
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_pizzicato_strings, 255, 216,0, 165  
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_flute, 245, 127, 231, 127  
	voice_noise 60, 0, 0, 0, 7, 0, 0 
    voice_square_1_alt 60, 0, 0, 2, 0, 1, 8, 1 
	voice_square_1_alt 60, 0, 0, 1, 0, 1, 5, 1
   	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_shamisen, 255, 200, 255, 250
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_shakuhachi, 255, 127, 231, 127 

 