	.align 2
voicegroup192:: @ 
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_dp_whistle_c5_16, 255, 247, 78, 196
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_dp_orchhitmajor60, 255, 200, 255, 171
	voice_directsound_no_resample 60, 0, DirectSoundWaveData_dp_orchhitminor60, 255, 200, 255, 171
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0											@ dummy
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_dp_sne1_roop, 255, 255, 191, 32
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_dp_handclup1, 255, 0, 227, 32
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_dp_sne2_loop, 255, 255, 191, 32
	voice_directsound_no_resample 48, 64, DirectSoundWaveData_dp_reverscyn_16, 2, 0, 255, 16
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_dp_bass2, 255, 0, 227, 32
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_dp_bassdr1, 255, 0, 227, 32
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_dp_808snare_16, 255, 220, 0, 64
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_dp_bassdr2_16, 255, 0, 255, 0
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_dp_bassdr1_16, 255, 0, 255, 171
	voice_directsound_no_resample 61, 58, DirectSoundWaveData_dp_rim1_roop, 255, 220, 0, 16
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_dp_oct_snare_16, 255, 0, 255, 0
	voice_directsound_no_resample 60, 70, DirectSoundWaveData_dp_053clap, 255, 0, 227, 32
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_dp_093snare, 255, 226, 127, 0
	voice_directsound_no_resample 29, 30, DirectSoundWaveData_dp_tom1_16, 255, 0, 255, 32
	voice_directsound_no_resample 60, 80, DirectSoundWaveData_dp_closed_hihat_16, 255, 0, 227, 32
	voice_directsound_no_resample 34, 40, DirectSoundWaveData_dp_tom1_16, 255, 0, 255, 32
	voice_directsound_no_resample 60, 80, DirectSoundWaveData_dp_pedalhight, 255, 0, 235, 16
	voice_directsound_no_resample 41, 50, DirectSoundWaveData_dp_tom1_16, 255, 0, 255, 32
	voice_directsound_no_resample 60, 80, DirectSoundWaveData_dp_open_hihat_16, 255, 241, 0, 0
	voice_directsound_no_resample 47, 100, DirectSoundWaveData_dp_tom1_16, 255, 0, 255, 32
	voice_directsound_no_resample 53, 107, DirectSoundWaveData_dp_tom1_16, 255, 0, 255, 32
	voice_directsound_no_resample 57, 64, DirectSoundWaveData_dp_cymbal1_16, 255, 246, 0, 214
	voice_directsound_no_resample 55, 117, DirectSoundWaveData_dp_tom1_16, 255, 0, 255, 16
	voice_directsound_no_resample 58, 30, DirectSoundWaveData_dp_ridecynbal, 255, 250, 0, 216
	voice_directsound_no_resample 59, 20, DirectSoundWaveData_dp_china_cynbal, 255, 250, 0, 226
	voice_directsound_no_resample 60, 30, DirectSoundWaveData_dp_ridecap, 255, 250, 0, 232
	voice_directsound_no_resample 60, 58, DirectSoundWaveData_dp_tambourine_16, 255, 0, 255, 32
	voice_directsound_no_resample 60, 84, DirectSoundWaveData_trinity_cymbal_crash, 255, 250, 0, 226
	voice_directsound_no_resample 60, 110, DirectSoundWaveData_dp_cawbell_16, 255, 0, 255, 176
	voice_directsound_no_resample 60, 36, DirectSoundWaveData_dp_cymbal1_16, 255, 250, 0, 216
	voice_directsound_no_resample 61, 102, DirectSoundWaveData_dp_cymbal1_16, 255, 250, 0, 216
	voice_directsound_no_resample 60, 86, DirectSoundWaveData_dp_ridecynbal, 255, 250, 0, 216
	voice_directsound_no_resample 60, 90, DirectSoundWaveData_dp_016bongo, 255, 0, 255, 176
	voice_directsound_no_resample 57, 90, DirectSoundWaveData_dp_016bongo, 255, 0, 255, 176
voice_directsound_no_resample 60, 20, DirectSoundWaveData_dp_mute_conga_16, 255, 0, 255, 176
	voice_directsound_no_resample 60, 24, DirectSoundWaveData_dp_060conga, 255, 0, 255, 176
	voice_directsound_no_resample 57, 26, DirectSoundWaveData_dp_060conga, 255, 0, 255, 176
	voice_directsound_no_resample 60, 26, DirectSoundWaveData_dp_africa_dr_16, 255, 0, 255, 176
	voice_directsound_no_resample 60, 101, DirectSoundWaveData_dp_africa_dr_16, 255, 0, 255, 176
	voice_directsound_no_resample 60, 26, DirectSoundWaveData_dp_cabassa_16, 255, 243, 127, 176
	voice_directsound_no_resample 60, 100, DirectSoundWaveData_dp_mute_conga_16, 255, 0, 255, 176
	voice_directsound_no_resample 60, 98, DirectSoundWaveData_dp_060conga, 255, 0, 255, 176
	voice_directsound_no_resample 63, 102, DirectSoundWaveData_dp_060conga, 255, 0, 255, 176
	voice_directsound_no_resample 60, 25, DirectSoundWaveData_dp_india_per_16, 255, 0, 255, 16
	voice_directsound_no_resample 60, 112, DirectSoundWaveData_dp_dragon_dr_16, 255, 0, 255, 16
	voice_directsound_no_resample 57, 100, DirectSoundWaveData_dp_dragon_dr_16, 255, 0, 255, 16
	voice_directsound_no_resample 55, 34, DirectSoundWaveData_dp_dragon_dr_16, 255, 0, 255, 16
	voice_directsound_no_resample 52, 22, DirectSoundWaveData_dp_dragon_dr_16, 255, 0, 255, 16
	voice_directsound_no_resample 59, 34, DirectSoundWaveData_dp_woodblock_16, 255, 0, 255, 176
	voice_directsound_no_resample 56, 90, DirectSoundWaveData_dp_woodblock_16, 255, 0, 255, 176
	voice_directsound_no_resample 54, 20, DirectSoundWaveData_dp_woodblock_16, 255, 0, 255, 0
	voice_directsound_no_resample 60, 107, DirectSoundWaveData_dp_woodblock_16, 255, 0, 255, 0
	voice_directsound 64, 44, DirectSoundWaveData_sd90_open_triangle, 255, 130, 150, 50
	voice_directsound 61, 44, DirectSoundWaveData_dp_triangle_16, 255, 200, 130, 0
	voice_directsound_no_resample 60, 90, DirectSoundWaveData_dp_sheiker, 255, 243, 111, 64
	voice_directsound_no_resample 60, 94, DirectSoundWaveData_dp_062sleigh, 255, 0, 255, 226
	voice_directsound_no_resample 70, 26, DirectSoundWaveData_dp_africa_dr_16, 255, 0, 255, 176
	voice_directsound_no_resample 54, 101, DirectSoundWaveData_dp_africa_dr_16, 255, 0, 255, 176
	voice_directsound_no_resample 65, 101, DirectSoundWaveData_dp_africa_dr_16, 255, 0, 255, 176
	voice_directsound_no_resample 60, 20, DirectSoundWaveData_dp_castanet_22, 255, 0, 255, 176
	voice_directsound_no_resample 60, 20, DirectSoundWaveData_dp_kaaroop_16, 255, 255, 191, 238
	voice_directsound_no_resample 48, 64, DirectSoundWaveData_dp_reverscyn_16, 2, 0, 255, 16
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_dp_bassdr2_16, 255, 0, 255, 0
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_dp_bassdr1_16, 255, 0, 255, 176
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_dp_oct_snare_16, 255, 0, 255, 0
	voice_directsound_no_resample 60, 70, DirectSoundWaveData_dp_053clap, 255, 0, 227, 32
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_dp_093snare, 255, 228, 127, 0
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_dp_bassdr1, 255, 0, 227, 32
	voice_directsound_no_resample 60, 58, DirectSoundWaveData_dp_808snare_16, 255, 222, 0, 64
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_dp_bass2, 255, 0, 227, 32
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_dp_bassdr1, 255, 0, 227, 32
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_dp_rim1_roop, 255, 255, 191, 16
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_dp_sne1_roop, 255, 255, 191, 32
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_dp_handclup1, 255, 0, 227, 32
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_dp_sne2_loop, 255, 255, 191, 32
	voice_directsound_no_resample 48, 30, DirectSoundWaveData_dp_tom_16, 255, 0, 255, 32
	voice_directsound_no_resample 60, 82, DirectSoundWaveData_dp_closehight_16, 255, 0, 227, 32
	voice_directsound_no_resample 53, 40, DirectSoundWaveData_dp_tom_16, 255, 0, 255, 32
	voice_directsound_no_resample 60, 82, DirectSoundWaveData_dp_pedalhight, 255, 0, 227, 32
	voice_directsound_no_resample 60, 50, DirectSoundWaveData_dp_tom_16, 255, 0, 255, 32
	voice_directsound_no_resample 60, 82, DirectSoundWaveData_dp_openhight, 254, 235, 0, 32
	voice_directsound_no_resample 66, 90, DirectSoundWaveData_dp_tom_16, 255, 0, 255, 32
	voice_directsound_no_resample 72, 100, DirectSoundWaveData_dp_tom_16, 255, 0, 255, 32
	voice_directsound_no_resample 57, 64, DirectSoundWaveData_dp_cymbal1_16, 255, 247, 0, 216
	voice_directsound_no_resample 74, 110, DirectSoundWaveData_dp_tom_16, 255, 0, 255, 16
	voice_directsound_no_resample 58, 30, DirectSoundWaveData_dp_ridecynbal, 255, 250, 0, 216
