#!/bin/bash

cp data/event_scripts.s build/event_scripts.s
sed -i '/^[[:space:]]*@ *hearth (autogenerated)[[:space:]]*$/,$ s/\.\(inc\)\(["'\'']\)/.scr\2/' build/event_scripts.s
cmp --quiet data/event_scripts.s build/event_scripts.s

if [ $? -eq 0 ]; then
	rm build/event_scripts.s
else
	mv build/event_scripts.s data/event_scripts.s
fi

exit 0
