#!/bin/bash

temp_file=$(mktemp)
sed '/^[[:space:]]*@ *hearth (autogenerated)[[:space:]]*$/,$ s/\.\(inc\)\(["'\'']\)/.scr\2/' data/event_scripts.s > "$temp_file"
cmp --quiet data/event_scripts.s "$temp_file"

if [ $? -eq 1 ]; then
	cp "$temp_file" data/event_scripts.s
fi

rm -f "$temp_file"

exit 0
