SpindaIsland_PlayerHome_Bedroom_MapScripts::
	.byte 0


SpindaIsland_PlayerHome_Bedroom_Diary::
# 6 "data/maps/SpindaIsland_PlayerHome_Bedroom/scripts.pory"
	lock
# 7 "data/maps/SpindaIsland_PlayerHome_Bedroom/scripts.pory"
	msgbox SpindaIsland_PlayerHome_Bedroom_Diary_Text_0
# 12 "data/maps/SpindaIsland_PlayerHome_Bedroom/scripts.pory"
	release
	return


SpindaIsland_PlayerHome_Bedroom_Diary_Text_0:
# 8 "data/maps/SpindaIsland_PlayerHome_Bedroom/scripts.pory"
	.string "“Dear diary,\n"
	.string "The ship is almost finished. It is\l"
	.string "gonna be awsome.\p"
	.string "It will be even more beautifull then\n"
	.string "dad's.”$"
