#ifndef GUARD_EVEN_LIVE_EVENT_CONSTANTS
#define GUARD_EVEN_LIVE_EVENT_CONSTANTS

enum LiveEvent
{
    LIVE_EVENT_NONE,
    LIVE_EVENT_HALT,
    LIVE_EVENT_WOOBAT_FLEE,
    LIVE_EVENT_SIGH,
    LIVE_EVENT_CHATOT,
    LIVE_EVENT_CROBAT_SHOP,
    LIVE_EVENT_DEERLING1_FLEE,
    LIVE_EVENT_DEERLING2_FLEE,
    LIVE_EVENT_COUNT
};

#endif
