#ifndef GUARD_CONSTANTS_FIELD_MUGSHOTS_H
#define GUARD_CONSTANTS_FIELD_MUGSHOTS_H

#define MUGSHOT_NONE  0
#define MUGSHOT_ARCHIE 1
#define MUGSHOT_LASS 2
#define MUGSHOT_MOM 3
#define MUGSHOT_LITTLE_BOY 4
#define MUGSHOT_LITTLE_GIRL 5
#define MUGSHOT_MAN 6
#define MUGSHOT_SUNBATHER 7
#define MUGSHOT_COUNT 8

#define EMOTE_NORMAL  0
#define EMOTE_GRINNING 1
#define EMOTE_THINKING 2
#define EMOTE_DISGUSTED 3
#define EMOTE_SAD 4
#define EMOTE_ANGRY 5
#define EMOTE_SURPRISED 6
#define EMOTE_SHOCKED 7
#define EMOTE_BLIND 8
#define EMOTE_EMBARRASSED 9
#define EMOTE_EXCITED 10
#define EMOTE_SWEAT 11
#define EMOTE_PENSIVE 12
#define EMOTE_HAPPY 13
#define EMOTE_COUNT  14

#endif // GUARD_CONSTANTS_FIELD_MUGSHOTS_H