#ifndef GUARD_CONSTANTS_FIELD_MUGSHOTS_H
#define GUARD_CONSTANTS_FIELD_MUGSHOTS_H

#define MUGSHOT_NONE  0
#define MUGSHOT_ARCHIE  1
#define MUGSHOT_COUNT 2

#define EMOTE_NORMAL  0
#define EMOTE_GRINNING 1
#define EMOTE_THINKING 2
#define EMOTE_DISGUSTED 3
#define EMOTE_SAD 4
#define EMOTE_ANGRY 5
#define EMOTE_COUNT   6

#endif // GUARD_CONSTANTS_FIELD_MUGSHOTS_H