#ifndef GUARD_CONSTANTS_FIELD_MUGSHOTS_H
#define GUARD_CONSTANTS_FIELD_MUGSHOTS_H

enum Mugshots {
    MUGSHOT_NONE = 0,
    MUGSHOT_TEST,
    MUGSHOT_HARIKO,
    MUGSHOT_NATSUKI,
    MUGSHOT_BIG_SIS,
    MUGSHOT_CLERK,
    MUGSHOT_CROBAT,
    MUGSHOT_ZUBAT,
    MUGSHOT_INCENSE,
    MUGSHOT_HANA,
    MUGSHOT_KOISHI,
    MUGSHOT_YUTAKA,
    MUGSHOT_KABA,
    MUGSHOT_MASQUERAIN_GIRL,
    MUGSHOT_OKADA,
    MUGSHOT_YOUNGSTER,
    MUGSHOT_SCHOOL_KID_F,
    MUGSHOT_SCHOOL_KID_M,
    MUGSHOT_BUG_CATCHER,
    MUGSHOT_AROMA_LADY,
    MUGSHOT_NINJA_BOY,
    MUGSHOT_LASS,
    MUGSHOT_MONK,
    MUGSHOT_HEX_MANIAC,
    MUGSHOT_ARTIST,
    MUGSHOT_BATTLE_GIRL,
    MUGSHOT_BATTLE_GUY,   // TODO
    MUGSHOT_HOT_SPRING_F,
    MUGSHOT_HOT_SPRING_M, // TODO
    MUGSHOT_COUNT,
};

enum MugshotEmotes {
    EMOTE_NORMAL = 0,
    EMOTE_SEXY,
    EMOTE_COUNT,
};

#endif // GUARD_CONSTANTS_FIELD_MUGSHOTS_H
