#ifndef FISH_SELLER_CONST_H
#define FISH_SELLER_CONST_H

enum {
    FISH_RARITY_COMMON,
    FISH_RARITY_UNCOMMON,
    FISH_RARITY_RARE,
    FISH_RARITY_RARE_AS_FUCK,
    TREASURE_COUNT,
};

#define TREASURE_PER_RARITY_COUNT 4
#define PRICE_FISH_COMMON         500
#define PRICE_FISH_UNCOMMON       1500
#define PRICE_FISH_RARE           4000
#define PRICE_FISH_RARE_AS_FUCK   6500
// 1/TREASURE_ODDS chance to find treasure
#define TREASURE_ODDS             2

#endif
