#ifndef GUARD_LIMITED_SHOP_CONSTANTS_H
#define GUARD_LIMITED_SHOP_CONSTANTS_H

#define LIMITED_SHOP_1  1
#define LIMITED_SHOP_2  2
#define LIMITED_SHOP_3  3
#define LIMITED_SHOP_4  4

#endif // GUARD_LIMITED_SHOP_CONSTANTS_H