#ifndef GUARD_CONSTANTS_POKEMON_MEMORIES_H
#define GUARD_CONSTANTS_POKEMON_MEMORIES_H

#define MON_MEMORY_ORIGIN 0
#define MON_MEMORY_OLD 1
#define MON_MEMORY_NEW 2

#define MEMORY_NONE 0
#define MEMORY_WENT_CAMPING 1
#define MEMORY_ELITE_FOUR 2

#define SPECIAL_MEMORIES_START (MEMORY_ELITE_FOUR)
#define MEMORY_COUNT (MEMORY_ELITE_FOUR + 1)

#endif  // GUARD_CONSTANTS_POKEMON_MEMORIES_H
