#ifndef GUARD_CONSTANTS_POKEMON_MEMORIES_H
#define GUARD_CONSTANTS_POKEMON_MEMORIES_H

#define MON_MEMORY_ORIGIN 0
#define MON_MEMORY_OLD 1
#define MON_MEMORY_NEW 2

enum MemoryGirlReadingResult {
    MEMORY_GIRL_READING_DONE,
    MEMORY_GIRL_READING_DIALOGUE,
    MEMORY_GIRL_READING_RIBBON_NOTIFICATION,
};

enum PokemonMemory {
    MEMORY_NONE,
    MEMORY_WENT_CAMPING,
    SPECIAL_MEMORIES_START,
    // Story events start here
    MEMORY_CLEARED_HIDEOUT = SPECIAL_MEMORIES_START,
    MEMORY_BEAT_DOJO,
    MEMORY_ELITE_FOUR,
    MEMORY_COUNT
};

#endif  // GUARD_CONSTANTS_POKEMON_MEMORIES_H
