#ifndef GUARD_CONSTANTS_SHAMISEN_PLAYERS_H
#define GUARD_CONSTANTS_SHAMISEN_PLAYERS_H

#define SHAMISEN_PLAYER_FLAG_TALKED_TODAY  0
#define SHAMISEN_PLAYER_FLAG_TALKED_BEFORE 1
#define SHAMISEN_PLAYER_FLAG_UNUSED_2      2
#define SHAMISEN_PLAYER_FLAG_UNUSED_3      3
#define SHAMISEN_PLAYER_FLAG_UNUSED_4      4
#define SHAMISEN_PLAYER_FLAG_UNUSED_5      5
#define SHAMISEN_PLAYER_FLAG_UNUSED_6      6
#define SHAMISEN_PLAYER_FLAG_UNUSED_7      7

#endif //GUARD_CONSTANTS__SHAMISEN_PLAYERS_H
