#ifndef GUARD_CONSTANTS_SHINY_VIAL_H
#define GUARD_CONSTANTS_SHINY_VIAL_H

#define NB_MINUTES_SHINY_VIAL_EFFECT 12 * 60
#define SHINY_VIAL_ADDITIONAL_ROLLS  10

#endif // GUARD_CONSTANTS_SHINY_VIAL_H
