#ifndef GUARD_CONSTANTS_SPEAKER_NAME_H
#define GUARD_CONSTANTS_SPEAKER_NAME_H

#define SPEAKER_NONE  0
#define SPEAKER_NATSUKI 1
#define SPEAKER_HARIKO  2
#define SPEAKER_COUNT  3

#endif // GUARD_CONSTANTS_SPEAKER_NAME_H
