#ifndef GUARD_TRAVELLING_MERCHANT_H
#define GUARD_TRAVELLING_MERCHANT_H

#define TRAVELLING_MERCHANT_SEED_MODIFIER  0xE59586E4
// 1/odds chance to sell a rare item
#define TRAVELLING_MERCHANT_RARE_ITEM_ODDS 2

#endif // GUARD_TRAVELLING_MERCHANT_H
