

gBirchDexRatingText_AreYouCurious::
	.string "PROF. BIRCH: Ah, {PLAYER}{KUN}!\p"
	.string "Are you curious about how your\n"
	.string "POKéDEX is coming along?$"

gBirchDexRatingText_Cancel::
	.string "Hm? Oh, you haven't caught enough\n"
	.string "Pokémon to make it worthwhile.$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "Hmhm…\p"
	.string "So, you've seen {STR_VAR_1} Pokémon,\n"
	.string "and you've caught {STR_VAR_2} POKéMON…$"

gBirchDexRatingText_LessThan10::
	.string "Go into grassy areas more and look\n"
	.string "for Pokémon more carefully.$"

gBirchDexRatingText_LessThan20::
	.string "I guess you're getting the hang\n"
	.string "of it. But, it gets harder from here.$"

gBirchDexRatingText_LessThan30::
	.string "Some Pokémon only appear in\n"
	.string "certain areas.\l"
	.string "You must be persistent.$"

gBirchDexRatingText_LessThan40::
	.string "Well, it could use more quantity,\n"
	.string "but this is looking more like\l"
	.string "a POKéDEX now.$"

gBirchDexRatingText_LessThan50::
	.string "This is coming along pretty good.\n"
	.string "Keep up the effort.$"

gBirchDexRatingText_LessThan60::
	.string "Are you using any RODS?\n"
	.string "There are many Pokémon in the sea.$"

gBirchDexRatingText_LessThan70::
	.string "Instead of just catching Pokémon,\n"
	.string "how about making them evolve, too?$"

gBirchDexRatingText_LessThan80::
	.string "This is going to be a fantastic\n"
	.string "POKéDEX.\l"
	.string "That's the feeling I'm getting.$"

gBirchDexRatingText_LessThan90::
	.string "You've collected this many…\n"
	.string "Your talent is remarkable!$"

gBirchDexRatingText_LessThan100::
	.string "Have you visited the SAFARI ZONE?\p"
	.string "I hear there are some Pokémon that\n"
	.string "can only be caught there.$"

gBirchDexRatingText_LessThan110::
	.string "You've finally reached\n"
	.string "the 100-kind mark.\p"
	.string "This is an impressive POKéDEX!$"

gBirchDexRatingText_LessThan120::
	.string "There might be Pokémon that can be\n"
	.string "found using ROCK SMASH.$"

gBirchDexRatingText_LessThan130::
	.string "You should get some more Pokémon\n"
	.string "by trading with others.$"

gBirchDexRatingText_LessThan140::
	.string "I've heard of Pokémon that evolve\n"
	.string "when they come to fully love their\l"
	.string "TRAINERS.$"

gBirchDexRatingText_LessThan150::
	.string "I had no idea that there were so\n"
	.string "many Pokémon species in the HOENN\l"
	.string "region.$"

gBirchDexRatingText_LessThan160::
	.string "On occasion, some Pokémon appear\n"
	.string "in large numbers like outbreaks.\p"
	.string "Don't miss opportunities like\n"
	.string "those.$"

gBirchDexRatingText_LessThan170::
	.string "One can get a very good idea about\n"
	.string "the Pokémon of the HOENN region\l"
	.string "by looking through your POKéDEX.$"

gBirchDexRatingText_LessThan180::
	.string "I would say you already qualify as\n"
	.string "a Pokémon PROFESSOR, and a good\l"
	.string "one, too!$"

gBirchDexRatingText_LessThan190::
	.string "With a POKéDEX this complete,\n"
	.string "you're a real professional at this!$"

gBirchDexRatingText_LessThan200::
	.string "You're very close to completing\n"
	.string "this POKéDEX.\l"
	.string "I can feel it in my bones!$"

gBirchDexRatingText_DexCompleted::
	.string "Congratulations!\n"
	.string "Your POKéDEX is complete!$"

gBirchDexRatingText_OnANationwideBasis::
	.string "Hmhm…\n"
	.string "On a nationwide basis…\p"
	.string "You've seen {STR_VAR_1} Pokémon,\n"
	.string "and you've caught {STR_VAR_2} POKéMON…$"

gHearthDexRatingText_LessThan10::
	.string "Do you walk around with your eyes\n"
	.string "closed or something? I know you can\l"
	.string "do better than that, {PLAYER}!$"

gHearthDexRatingText_LessThan20::
	.string "Hmm, you should research the Pokémon\n"
	.string "you've glimpsed by asking around, too.\p"
	.string "Also, please work on your handwriting\n"
	.string "for next time…$"

gHearthDexRatingText_LessThan30::
	.string "Visit the same area at night for a\n"
	.string "chance to meet more Pokémon.$"

gHearthDexRatingText_LessThan40::
	.string "This actually isn't too bad.\n"
	.string "And I guess your calligraphy improved\l"
	.string "a little, as well.$"

gHearthDexRatingText_LessThan50::
	.string "It shall take courage and\n"
	.string "perseverance to see this through,\l"
	.string "but it is coming along.\p"
	.string "Could you avoid making so many ink\n"
	.string "blotches, though?$"

gHearthDexRatingText_LessThan60::
	.string "Fishing, swimming, breaking rocks…\n"
	.string "Explore in every way possible to ink\l"
	.string "these pages further!$"

gHearthDexRatingText_LessThan70::
	.string "You've caught quite a lot of critters,\n"
	.string "but do you spend time making them\l"
	.string "evolve?\l"
	.string "It's easier to sketch up a Pokémon\l"
	.string "that isn't scuttling around!$"

gHearthDexRatingText_LessThan80::
	.string "This PokéDex is becoming quite\n"
	.string "comprehensive.\p"
	.string "You should be proud of what you've\n"
	.string "accomplished so far!$"

gHearthDexRatingText_LessThan90::
	.string "So many drawings, so many precise\n"
	.string "descriptions!\p"
	.string "I am glad I gave you this task.$"

gHearthDexRatingText_LessThan100::
	.string "I heard there were many fascinating\n"
	.string "creatures in the great sea.\l"
	.string "Have you explored that area with your\l"
	.string "Pokémon?$"

gHearthDexRatingText_LessThan110::
	.string "The cover may be scratched and torn,\n"
	.string "but this is an impressive PokéDex!$"

gHearthDexRatingText_LessThan120::
	.string "There might be Pokémon that can be\n"
	.string "found using ROCK SMASH.$"

gHearthDexRatingText_LessThan130::
	.string "You should get some more Pokémon\n"
	.string "by trading with others.$"

gHearthDexRatingText_LessThan140::
	.string "I've heard of Pokémon that evolve\n"
	.string "when they come to fully love their\l"
	.string "TRAINERS.$"

gHearthDexRatingText_LessThan150::
	.string "I had no idea that there were so\n"
	.string "many Pokémon species in the HOENN\l"
	.string "region.$"

gHearthDexRatingText_LessThan160::
	.string "On occasion, some Pokémon appear\n"
	.string "in large numbers like outbreaks.\p"
	.string "Don't miss opportunities like\n"
	.string "those.$"

gHearthDexRatingText_LessThan170::
	.string "One can get a very good idea about\n"
	.string "the Pokémon of the HOENN region\l"
	.string "by looking through your POKéDEX.$"

gHearthDexRatingText_LessThan180::
	.string "I would say you already qualify as\n"
	.string "a Pokémon PROFESSOR, and a good\l"
	.string "one, too!$"

gHearthDexRatingText_LessThan190::
	.string "With a POKéDEX this complete,\n"
	.string "you're a real professional at this!$"

gHearthDexRatingText_LessThan200::
	.string "You're very close to completing\n"
	.string "this POKéDEX.\l"
	.string "I can feel it in my bones!$"

gHearthDexRatingText_DexCompleted::
	.string "Congratulations!\n"
	.string "Your POKéDEX is complete!$"

gHearthDexRatingText_OnANationwideBasis::
	.string "Hmhm…\n"
	.string "On a nationwide basis…\p"
	.string "You've seen {STR_VAR_1} Pokémon,\n"
	.string "and you've caught {STR_VAR_2} Pokémon$"
