name: :fire: Hearth dev bug report
description: Bugs found during development
labels: ["bug", "status: unconfirmed"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Describe the issue you are experiencing.
        Attach images/videos if possible.
      placeholder: |
        Please enter a description of the issue. Here you can also attach log screenshots, gifs or a video
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: |
        Describe the expected behavior.
      placeholder: |
    validations:
      required: true
  - type: textarea
    id: observed
    attributes:
      label: Observed behavior
      description: |
        Describe the observed behavior.
      placeholder: |
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: |
        List the steps to reproduce the issue.
      placeholder: |
    validations:
      required: true
  - type: input
    id: branch
    attributes:
      label: Branch
      description: What branch does this bug appear on?
    validations:
      required: true
