# 2 "data/scripts/check_furniture.pory"

# 3 "data/scripts/check_furniture.pory"
EventScript_PictureBookShelf::
# 4 "data/scripts/check_furniture.pory"
	msgbox Text_PictureBookShelf, MSGBOX_SIGN
# 5 "data/scripts/check_furniture.pory"
	end
# 6 "data/scripts/check_furniture.pory"

# 7 "data/scripts/check_furniture.pory"
EventScript_BookShelf::
# 8 "data/scripts/check_furniture.pory"
	msgbox Text_BookShelf, MSGBOX_SIGN
# 9 "data/scripts/check_furniture.pory"
	end
# 10 "data/scripts/check_furniture.pory"

# 11 "data/scripts/check_furniture.pory"
EventScript_PokemonCenterBookShelf::
# 12 "data/scripts/check_furniture.pory"
	msgbox Text_PokemonCenterBookShelf, MSGBOX_SIGN
# 13 "data/scripts/check_furniture.pory"
	end
# 14 "data/scripts/check_furniture.pory"

# 15 "data/scripts/check_furniture.pory"
EventScript_Vase::
# 16 "data/scripts/check_furniture.pory"
	msgbox Text_Vase, MSGBOX_SIGN
# 17 "data/scripts/check_furniture.pory"
	end
# 18 "data/scripts/check_furniture.pory"

# 19 "data/scripts/check_furniture.pory"
EventScript_EmptyTrashCan::
# 20 "data/scripts/check_furniture.pory"
	msgbox Text_EmptyTrashCan, MSGBOX_SIGN
# 21 "data/scripts/check_furniture.pory"
	end
# 22 "data/scripts/check_furniture.pory"

# 23 "data/scripts/check_furniture.pory"
EventScript_ShopShelf::
# 24 "data/scripts/check_furniture.pory"
	msgbox Text_ShopShelf, MSGBOX_SIGN
# 25 "data/scripts/check_furniture.pory"
	end
# 26 "data/scripts/check_furniture.pory"

# 27 "data/scripts/check_furniture.pory"
EventScript_Blueprint::
# 28 "data/scripts/check_furniture.pory"
	msgbox Text_Blueprint, MSGBOX_SIGN
# 29 "data/scripts/check_furniture.pory"
	end
