SpindaIsland_Home_MapScripts::
	.byte 0


SpindaIsland_Home_EventScript_HidingBoy::
# 6 "data/maps/SpindaIsland_Home/scripts.pory"
	speakername SpindaIsland_Home_EventScript_HidingBoy_Text_0
# 7 "data/maps/SpindaIsland_Home/scripts.pory"
	msgbox SpindaIsland_Home_EventScript_HidingBoy_Text_1, MSGBOX_NPC
	return


SpindaIsland_Home_EventScript_HidingBoy_Text_0:
# 6 "data/maps/SpindaIsland_Home/scripts.pory"
	.string "mmmmmmmmmmmmmmmmmmmmm$"

SpindaIsland_Home_EventScript_HidingBoy_Text_1:
# 8 "data/maps/SpindaIsland_Home/scripts.pory"
	.string "DARN! You found me!!$"
