#ifndef FISH_SELLER_DEFINES_H
#define FISH_SELLER_DEFINES_H

#include "constants/fish_seller.h"

struct FishMon
{
    u16 species;
    u16 rarity;
};

const struct FishMon sAcceptedFish[] = {
    {SPECIES_FROAKIE, FISH_RARITY_UNCOMMON},
    {SPECIES_FROGADIER, FISH_RARITY_UNCOMMON},
    {SPECIES_GRENINJA, FISH_RARITY_RARE},
    {SPECIES_TENTACOOL, FISH_RARITY_COMMON},
    {SPECIES_TENTACRUEL, FISH_RARITY_COMMON},
    {SPECIES_QWILFISH, FISH_RARITY_COMMON},
    {SPECIES_OVERQWIL, FISH_RARITY_UNCOMMON},
    {SPECIES_CHINCHOU, FISH_RARITY_COMMON},
    {SPECIES_LANTURN, FISH_RARITY_UNCOMMON},
    {SPECIES_CARVANHA, FISH_RARITY_COMMON},
    {SPECIES_SHARPEDO, FISH_RARITY_UNCOMMON},
    {SPECIES_WAILMER, FISH_RARITY_UNCOMMON},
    {SPECIES_WAILORD, FISH_RARITY_RARE},
    {SPECIES_WISHIWASHI, FISH_RARITY_RARE},
    {SPECIES_VELUZA, FISH_RARITY_UNCOMMON},
    {SPECIES_DONDOZO, FISH_RARITY_UNCOMMON},
    {SPECIES_TATSUGIRI, FISH_RARITY_UNCOMMON},
    {SPECIES_LAPRAS, FISH_RARITY_RARE_AS_FUCK},
    {SPECIES_HORSEA, FISH_RARITY_COMMON},
    {SPECIES_SEADRA, FISH_RARITY_UNCOMMON},
    {SPECIES_KINGDRA, FISH_RARITY_RARE_AS_FUCK},
    {SPECIES_SKRELP, FISH_RARITY_COMMON},
    {SPECIES_DRAGALGE, FISH_RARITY_UNCOMMON},
    {SPECIES_KRABBY, FISH_RARITY_COMMON},
    {SPECIES_KINGLER, FISH_RARITY_UNCOMMON},
    {SPECIES_KLAWF, FISH_RARITY_UNCOMMON},
    {SPECIES_DWEBBLE, FISH_RARITY_COMMON},
    {SPECIES_CRUSTLE, FISH_RARITY_UNCOMMON},
    {SPECIES_SHELLOS, FISH_RARITY_COMMON},
    {SPECIES_GASTRODON, FISH_RARITY_UNCOMMON},
    {SPECIES_FEEBAS, FISH_RARITY_RARE},
    {SPECIES_MILOTIC, FISH_RARITY_RARE_AS_FUCK},
    {SPECIES_MAGIKARP, FISH_RARITY_COMMON},
    {SPECIES_GYARADOS, FISH_RARITY_UNCOMMON},
    {SPECIES_DRATINI, FISH_RARITY_RARE},
    {SPECIES_DRAGONAIR, FISH_RARITY_RARE},
    {SPECIES_DRAGONITE, FISH_RARITY_RARE_AS_FUCK},
    {SPECIES_NONE, TREASURE_COUNT},
};

const u32 sfoundTreasures[TREASURE_COUNT][TREASURE_PER_RARITY_COUNT] = {
    [FISH_RARITY_COMMON] = {ITEM_KELPSY_BERRY, ITEM_KELPSY_BERRY, ITEM_LURE_BALL, ITEM_LURE_BALL},
    [FISH_RARITY_UNCOMMON] = {ITEM_NET_BALL, ITEM_NET_BALL, ITEM_PEARL, ITEM_HEART_SCALE},
    [FISH_RARITY_RARE] = {ITEM_KINGS_ROCK, ITEM_BIG_PEARL, ITEM_WATER_STONE, ITEM_HEART_SCALE},
    [FISH_RARITY_RARE_AS_FUCK] = {ITEM_PEARL_STRING, ITEM_PRISM_SCALE, ITEM_MYSTIC_WATER, ITEM_DRAGON_SCALE},
};

#endif // FISH_SELLER_DEFINES_H
