#define REPEAT_1(x)  (x)
#define REPEAT_2(x)  (x, x)
#define REPEAT_3(x)  (x, x, x)
#define REPEAT_4(x)  (x, x, x, x)
#define REPEAT_5(x)  (x, x, x, x, x)
#define REPEAT_6(x)  (x, x, x, x, x, x)
#define REPEAT_7(x)  (x, x, x, x, x, x, x)
#define REPEAT_8(x)  (x, x, x, x, x, x, x, x)
#define REPEAT_9(x)  (x, x, x, x, x, x, x, x, x)
#define REPEAT_10(x) (x, x, x, x, x, x, x, x, x, x)
#define REPEAT_11(x) (x, x, x, x, x, x, x, x, x, x, x)
#define REPEAT_12(x) (x, x, x, x, x, x, x, x, x, x, x, x)
#define REPEAT_13(x) (x, x, x, x, x, x, x, x, x, x, x, x, x)
#define REPEAT_14(x) (x, x, x, x, x, x, x, x, x, x, x, x, x, x)
#define REPEAT_15(x) (x, x, x, x, x, x, x, x, x, x, x, x, x, x, x)
#define REPEAT_16(x) (x, x, x, x, x, x, x, x, x, x, x, x, x, x, x, x)

#define REPEAT_N(n, x) CAT(REPEAT_, n)(x)

#define NUMBERS_16 (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15)
